import { AbilityConstant, ConfigurationConstant, UIAbility, Want } from '@kit.AbilityKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { window } from '@kit.ArkUI';
import { IBestInit, IBestSetUIBaseStyle } from 'ui';
import { MainGraph } from 'main';

const DOMAIN = 0x0000;

/**
 * 入口Ability
 * 负责初始化应用、设置路由、处理生命周期事件
 * @author Joker.X
 */
export default class EntryAbility extends UIAbility {
  /**
   * 应用创建时调用
   * 初始化应用上下文、设置颜色模式、注册路由
   * @param {Want} want - 启动意图
   * @param {AbilityConstant.LaunchParam} launchParam - 启动参数
   * @returns {void} 无返回值
   */
  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    try {
      this.context.getApplicationContext().setColorMode(ConfigurationConstant.ColorMode.COLOR_MODE_NOT_SET);
      this.registerRouter();
    } catch (err) {
      hilog.error(DOMAIN, 'testTag', 'Failed to set colorMode. Cause: %{public}s', JSON.stringify(err));
    }
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onCreate');
  }

  /**
   * 窗口创建时调用
   * 加载入口页面、初始化UI基础样式
   * @param {window.WindowStage} windowStage - 窗口阶段
   * @returns {Promise<void>} 无返回值的Promise
   */
  async onWindowStageCreate(windowStage: window.WindowStage): Promise<void> {
    windowStage.loadContent('view/EntryPage', (_) => {
      IBestInit(windowStage, this.context)
      IBestSetUIBaseStyle({
        primary: $r('app.color.primary'),
        success: $r('app.color.success'),
        warning: $r('app.color.warning'),
        danger: $r('app.color.danger'),
      })
    });
  }

  /**
   * 应用销毁时调用
   * 释放应用上下文、注销路由
   * @returns {void} 无返回值
   */
  onDestroy(): void {
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onDestroy');
  }

  /**
   * 窗口销毁时调用
   * 释放窗口资源
   * @returns {void} 无返回值
   */
  onWindowStageDestroy(): void {
  }

  /**
   * 应用进入前台时调用
   * 刷新应用状态、重新注册路由
   * @returns {void} 无返回值
   */
  onForeground(): void {
  }

  /**
   * 应用进入后台时调用
   * 暂停应用状态、注销路由
   * @returns {void} 无返回值
   */
  onBackground(): void {
  }

  /**
   * 注册路由
   */
  registerRouter() {
    new MainGraph().register();
  }
}